    # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.16.5 is version 36
    loaderVersion="[36,)"
    # The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
    # Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
    license="MIT"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/TeamKuiper/Redoxiation/issues"
    # If the mods defined in this file should show as separate resource packs
    showAsResourcePack=false

    [[mods]]
      modId="redoxiation"
      version="0.0.0.1"
      displayName="Redoxiation"
      updateJSONURL="https://minecraftforge.net/versions.json"
      displayURL="https://minecraftforge.net"
      logoFile="logo.png"
      credits="Oxidation-Reduction!"
      authors="Team Kuiper"
      description="Realistic tech mod."

      [[dependencies.redoxiation]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.redoxiation]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5,1.17)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.redoxiation]]
        modId="codechickenlib"
        mandatory=true
        versionRange="[4.0.7.445,)"
        ordering="NONE"
        side="BOTH"